#!/usr/bin/env node
// Batch validator for Groq Llama 4 Scout damage classification.
//
// Usage:
//   1. npm run dev   (in another shell — keeps /api/ai/classify alive on port 3000)
//   2. mkdir -p data/damage-samples  (already gitignored)
//   3. Drop photos in data/damage-samples/ and create data/damage-samples/labels.json:
//      [
//        { "filename": "img001.webp", "ground_truth_severity": "severe",     "source": "xBD/hurricane-michael" },
//        { "filename": "img002.jpg",  "ground_truth_severity": "negligible", "source": "Copernicus EMS EMSR512" },
//        ...
//      ]
//   4. node scripts/validate-ai.mjs   (overwrites docs/AI_VALIDATION.md with results)

import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const SAMPLES_DIR = path.resolve('data/damage-samples')
const LABELS_FILE = path.join(SAMPLES_DIR, 'labels.json')
const REPORT_FILE = path.resolve('docs/AI_VALIDATION.md')
const ENDPOINT = process.env.CLASSIFY_URL ?? 'http://localhost:3000/api/ai/classify'

const SEVERITY_ORDER = ['negligible', 'moderate', 'severe', 'destroyed', 'unknown']

const MIME_BY_EXT = {
  '.webp': 'image/webp',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
}

async function main() {
  let labels
  try {
    labels = JSON.parse(await readFile(LABELS_FILE, 'utf8'))
  } catch (e) {
    console.error(`Could not read ${LABELS_FILE}. Create it as described in the script header.`)
    process.exit(1)
  }
  if (!Array.isArray(labels) || labels.length === 0) {
    console.error(`${LABELS_FILE} must be a non-empty JSON array.`)
    process.exit(1)
  }

  const results = []
  for (let i = 0; i < labels.length; i++) {
    const label = labels[i]
    const filepath = path.join(SAMPLES_DIR, label.filename)
    const ext = path.extname(label.filename).toLowerCase()
    const mime = MIME_BY_EXT[ext]
    if (!mime) {
      console.warn(`[${i + 1}/${labels.length}] ${label.filename}: unsupported extension, skipping`)
      continue
    }

    const buf = await readFile(filepath)
    const blob = new Blob([buf], { type: mime })
    const fd = new FormData()
    fd.append('photo', blob, label.filename)

    process.stdout.write(`[${i + 1}/${labels.length}] ${label.filename} → `)
    try {
      const res = await fetch(ENDPOINT, { method: 'POST', body: fd })
      if (!res.ok) {
        console.log(`HTTP ${res.status}`)
        continue
      }
      const json = await res.json()
      results.push({
        filename: label.filename,
        truth: label.ground_truth_severity,
        predicted: json.severity,
        confidence: json.confidence,
        damage_percentage: json.damage_percentage,
        provider: json._meta?.provider,
        source: label.source,
      })
      console.log(`predicted=${json.severity} (truth=${label.ground_truth_severity}, conf=${json.confidence.toFixed(2)})`)
    } catch (e) {
      console.log(`error: ${e.message}`)
    }
  }

  await writeReport(results, labels.length)
  console.log(`\nReport written to ${REPORT_FILE}`)
}

async function writeReport(results, totalAttempted) {
  const exactMatches = results.filter(r => r.predicted === r.truth)
  const nearMatches = results.filter(r => {
    if (r.predicted === r.truth) return false
    // 'unknown' means "AI couldn't assess" — not a damage tier. Treating it as
    // adjacent to 'destroyed' (the array layout would imply that) would inflate
    // the near-match rate. Exclude it from either axis.
    if (r.predicted === 'unknown' || r.truth === 'unknown') return false
    const ti = SEVERITY_ORDER.indexOf(r.truth)
    const pi = SEVERITY_ORDER.indexOf(r.predicted)
    return Math.abs(ti - pi) === 1
  })
  const falsePositives = results.filter(r =>
    r.truth === 'negligible' && r.predicted !== 'negligible' && r.predicted !== 'unknown'
  )
  const falseNegatives = results.filter(r =>
    (r.truth === 'severe' || r.truth === 'destroyed') && r.predicted === 'negligible'
  )

  const meanConf = (rows) =>
    rows.length === 0 ? 0 : rows.reduce((a, r) => a + r.confidence, 0) / rows.length

  const truthCounts = SEVERITY_ORDER.reduce((acc, s) => {
    acc[s] = results.filter(r => r.truth === s).length
    return acc
  }, {})

  const matrix = {}
  for (const t of SEVERITY_ORDER) {
    matrix[t] = {}
    for (const p of SEVERITY_ORDER) {
      matrix[t][p] = results.filter(r => r.truth === t && r.predicted === p).length
    }
  }

  const sources = [...new Set(results.map(r => r.source).filter(Boolean))]

  const N = results.length
  const pct = (n) => N === 0 ? '0%' : `${((n / N) * 100).toFixed(1)}%`

  const md = `# AI Validation Report

Generated by \`scripts/validate-ai.mjs\` at ${new Date().toISOString()}.

## Dataset

- **Source(s):** ${sources.join(', ') || 'unknown'}
- **Photos attempted:** ${totalAttempted}
- **Photos scored:** ${N}
- **Severity distribution (ground truth):**
${SEVERITY_ORDER.map(s => `  - ${s}: ${truthCounts[s]}`).join('\n')}

## Accuracy summary

| Metric | Value |
| --- | --- |
| Exact severity match | ${exactMatches.length} / ${N} (${pct(exactMatches.length)}) |
| Near match (one tier off) | ${nearMatches.length} / ${N} (${pct(nearMatches.length)}) |
| False positives (truth=negligible, predicted=damaged) | ${falsePositives.length} |
| False negatives (truth=severe/destroyed, predicted=negligible) | ${falseNegatives.length} |
| Mean confidence overall | ${meanConf(results).toFixed(3)} |
| Mean confidence on matches | ${meanConf(exactMatches).toFixed(3)} |
| Mean confidence on misses | ${meanConf(results.filter(r => r.predicted !== r.truth)).toFixed(3)} |

## Confusion matrix

|  | ${SEVERITY_ORDER.map(p => `predicted ${p}`).join(' | ')} |
| --- | ${SEVERITY_ORDER.map(() => '---').join(' | ')} |
${SEVERITY_ORDER.map(t => `| actual ${t} | ${SEVERITY_ORDER.map(p => matrix[t][p]).join(' | ')} |`).join('\n')}

## Provider mix

${(() => {
  const counts = {}
  for (const r of results) counts[r.provider] = (counts[r.provider] || 0) + 1
  return Object.entries(counts).map(([p, c]) => `- ${p}: ${c}`).join('\n')
})()}

## Assumptions

- Ground-level or near-ground-level photos only — Copernicus EMS top-down satellite imagery is excluded.
- Photos pre-compressed to ≤200 KB WebP (matching what a reporter's device sends).
- Ground-truth labels mapped to the Copernicus EMS 4-tier scale (\`negligible\` / \`moderate\` / \`severe\` / \`destroyed\`).

## Per-photo log

| filename | truth | predicted | confidence | provider |
| --- | --- | --- | --- | --- |
${results.map(r => `| ${r.filename} | ${r.truth} | ${r.predicted} | ${r.confidence.toFixed(2)} | ${r.provider ?? '?'} |`).join('\n')}
`

  return writeFile(REPORT_FILE, md)
}

main().catch(e => {
  console.error(e)
  process.exit(1)
})
